name: Test Query 01
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    paths: [ '**/run_tests.sh', '**01**' ]

jobs:
  build:

    runs-on: ubuntu-latest

    # Use the postgis image to start a postgres service
    #
    # See the following links for more information:
    # https://hub.docker.com/_/postgis
    # https://docs.github.com/en/actions/guides/about-service-containers
    # https://docs.github.com/en/actions/guides/creating-postgresql-service-containers
    services:
      postgres:
        # Hardcoding the image name here. Would rather use ${{ github.repository }},
        # but there may not be any uppercase characters in the name.
        image: ghcr.io/weitzman-musa-geocloud/assignment02:main
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js 16.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install JS dependencies
      run: |
        npm install
        npm install -g dotenv-cli

    - name: Install PostgreSQL Client
      run: sudo apt install -y postgresql-client

    - name: Initialize DB connection variables
      run: cp .env.template .env

    - name: Apply database customizations
      run: dotenv __scripts__/apply_customizations.sh

    - name: Run tests
      run: |
        npm test __tests__/test_query01.js
